modification in http collector
gojuno/zipkin-go-opentracing pull request #1
Opened 2017-05-05 10:58 UTC by mkabischev

2017-05-05 11:35 UTC, sbinq commented on collector-http.go
> +		c.logger.Log("err", err)
so this would be logged twice?

2017-05-05 11:42 UTC, mkabischev commented on collector-http.go
> +		c.logger.Log("err", err)
fixed, thx

2017-05-05 13:25 UTC, mkorolyov requested changes

2017-05-05 13:25 UTC, mkorolyov commented on collector-http_test.go
> -func TestHttpCollector_MaxBatchSize(t *testing.T) {
add check that code isn't blocking if http request hangs?

2017-05-05 14:59 UTC, hexdigest commented on collector-http.go
> +	if len(b) == 0 {
Maybe it's better to put this if statement above the defer?

2017-05-08 07:00 UTC, mkabischev commented on collector-http.go
> +	if len(b) == 0 {
Even if buffer is empty it must be returned to pool.

2017-05-08 08:21 UTC, mkorolyov approved these changes

2017-05-08 08:21 UTC, mkabischev commented on collector-http_test.go
> -func TestHttpCollector_MaxBatchSize(t *testing.T) {
There is test for this case: TestHttpCollector_NonBlockCollect, but it did nothing before. I`ve updated ot

2017-05-08 08:44 UTC, merged